name: Build ISO
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm xorriso grub-common grub-pc-bin mtools gcc-multilib
      - name: Build OS
        run: |
          echo '[BITS 32]
          section.multiboot
          align 4
          dd 0x1BADB002
          dd 0x00
          dd -0x1BADB002
          section.text
          global _start
          _start:
            mov esp, 0x90000
            call kmain
            cli
         .hang:
            hlt
            jmp.hang' > boot.asm
          echo 'void kmain(){ char *v= (char*)0xB8000; char *s="BroOS Running!"; int i=0; while(s[i]){ v[i*2]=s[i]; v[i*2+1]=0x0E; i++; } while(1){}}' > kernel.c
          nasm -f elf32 boot.asm -o boot.o
          gcc -m32 -ffreestanding -fno-stack-protector -c kernel.c -o kernel.o
          ld -m elf_i386 -Ttext 0x100000 -o kernel.elf boot.o kernel.o --oformat elf32-i386
          mkdir -p iso/boot/grub
          cp kernel.elf iso/boot/kernel.bin
          echo 'menuentry "BroOS"{ multiboot /boot/kernel.bin }' > iso/boot/grub/grub.cfg
          grub-mkrescue -o BroOS.iso iso
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: BroOS-ISO
          path: BroOS.iso
